### ISSUE TITLE
ActionController::RoutingError (uninitialized constant PipelineController):

### ISSUE THREAD

**Issue by yecine06** [GitDries/redmine_pipeline_plugin#3]
When i try to go to the pipeline view i have an error on the routing.

I have redmine 2.3

here is the content of the log file

```
Started GET "/pipeline/report" at Tue Mar 12 08:52:46 +0100 2013
```

ActionController::RoutingError (uninitialized constant PipelineController):
  activesupport (3.2.12) lib/active_support/inflector/methods.rb:219:in `constantize'
  activesupport (3.2.12) lib/active_support/inflector/methods.rb:218:in`each'
  activesupport (3.2.12) lib/active_support/inflector/methods.rb:218:in `constantize'
  actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:69:in`controller_reference'
  actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:54:in `controller'
  actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:32:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:601:in`call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.12) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
.....

**Comment by yecine06** [comment]
Nevermind, when i cloned the repository the folder name was having dash instead of underscores

a simple `mv plugins/redmine-pipeline-plugin plugins/redmine_pipeline_plugin` solved the problem

**Comment by gotva** [comment]
+1 the same

it is better to name repository using "_" not "-"

**Comment by GitDries** [comment]
Thanks for the feedback.

I've changed the repo-name.
Hopefully I didn't cause many dead-links
